services:
  php:
    image: computisazcr.azurecr.io/pulse-php:latest
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"

  nginx:
    image: computisazcr.azurecr.io/pulse-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php
