services:
  php:
    container_name: pulse_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - sqlite_data:/var/www/var
    environment:
      APP_ENV: ${APP_ENV}
    networks:
      - pulse_network

  nginx:
    container_name: pulse_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - pulse_network

networks:
  pulse_network:

volumes:
  sqlite_data:
  