# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    NINJAONE_API_URL.api_url: '%env(NINJAONE_API_URL)%'
    NINJAONE_GRANT_TYPE.grant_type: '%env(NINJAONE_GRANT_TYPE)%'
    NINJAONE_API_CLIENT_ID.client_id: '%env(NINJAONE_CLIENT_ID)%'
    NINJAONE_API_CLIENT_SECRET.client_secret: '%env(NINJAONE_CLIENT_SECRET)%'
    NINJAONE_SCOPE.scope: '%env(NINJAONE_SCOPE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

        App\Service\NinjaOneApiService:
            arguments:
                $ninjaOneApiUrl: '%NINJAONE_API_URL.api_url%'
                $ninjaOneGrantType: '%NINJAONE_GRANT_TYPE.grant_type%'
                $ninjaOneApiClientId: '%NINJAONE_API_CLIENT_ID.client_id%'
                $ninjaOneApiClientSecret: '%NINJAONE_API_CLIENT_SECRET.client_secret%'
                $ninjaOneScope: '%NINJAONE_SCOPE.scope%'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
